name: Bump version

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Type of version (major / minor / patch)"
        required: true

jobs:
  bump-version:
    name: Bump version
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Setup Git
        run: |
          git config user.name '${{ secrets.GIT_USER_NAME }}'
          git config user.email '${{ secrets.GIT_USER_EMAIL }}'
      - name: bump version
        run: npm version ${{ github.event.inputs.version }}
      - run: bun run quality:fix
      - name: Push latest version
        run: git push origin main --follow-tags
